version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker.io"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/quay.io"
    schedule:
      interval: "monthly"

