version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker.io"
    registries:
      - dockerhub # Allow version updates for dependencies in this registry
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/quay.io"
    schedule:
      interval: "monthly"